# Generated by Django 6.0.1 on 2026-01-21 07:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, verbose_name='Название мероприятия')),
                ('description', models.CharField(max_length=500, verbose_name='Описание мероприятия')),
                ('start_date', models.DateTimeField(auto_now=True, verbose_name='Дата начала')),
                ('end_date', models.DateTimeField(verbose_name='Дата завершения')),
                ('pub_date', models.DateTimeField(verbose_name='Дата публикации')),
                ('author', models.CharField(max_length=50, verbose_name='Автор')),
                ('top', models.IntegerField(default=1, help_text='Рейтинг от 0 до 25', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(25)], verbose_name='Рейтинг')),
                ('status', models.CharField(choices=[('draft', 'черновик'), ('later publication', 'отложенная публикация'), ('publication', 'опубликовано'), ('publication', 'архив')], default='draft', max_length=40)),
            ],
        ),
    ]
