# Generated by Django 6.0.1 on 2026-01-21 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_alter_event_options_alter_eventimage_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventimage',
            name='array',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='eventimage',
            name='b_preview',
            field=models.BooleanField(default=False, verbose_name='Главное изображение'),
        ),
    ]
