# Generated by Django 6.0.1 on 2026-01-21 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_eventimage_array_eventimage_b_preview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventimage',
            name='array',
        ),
        migrations.RemoveField(
            model_name='eventimage',
            name='b_preview',
        ),
    ]
