# Generated by Django 6.0.1 on 2026-01-22 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_remove_eventimage_array_remove_eventimage_b_preview'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventimage',
            name='b_preview',
            field=models.BooleanField(default=False, verbose_name='Главное изображение'),
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('draft', 'черновик'), ('later publication', 'отложенная публикация'), ('publication', 'опубликовано'), ('archive', 'архив')], default='draft', max_length=40, verbose_name='Статус'),
        ),
    ]
