# Generated by Django 6.0.1 on 2026-01-22 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_eventimage_b_preview_alter_event_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('later publication', 'Отложенная публикация'), ('publication', 'Опубликовано'), ('archive', 'Архив')], default='draft', max_length=40, verbose_name='Статус'),
        ),
    ]
