# Generated by Django 6.0.1 on 2026-01-20 14:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'verbose_name': 'Место проведения', 'verbose_name_plural': 'Локации'},
        ),
        migrations.AlterField(
            model_name='location',
            name='coordinateY',
            field=models.DecimalField(decimal_places=8, help_text='От -180.0 (запад) до 180.0 (восток)', max_digits=11, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)], verbose_name='Долгота'),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Название места'),
        ),
    ]
