# Generated by Django 6.0.1 on 2026-01-20 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_alter_location_options_alter_location_coordinatey_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='coordinateX',
            field=models.DecimalField(decimal_places=8, help_text='От -90.0(юг) до 90.0 (север)', max_digits=10, verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='location',
            name='coordinateY',
            field=models.DecimalField(decimal_places=8, help_text='От -180.0 (запад) до 180.0 (восток)', max_digits=11, verbose_name='Долгота'),
        ),
    ]
