# Generated by Django 6.0.1 on 2026-01-20 14:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0003_alter_location_coordinatex_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'verbose_name': 'локацию', 'verbose_name_plural': 'Локации'},
        ),
        migrations.AddField(
            model_name='location',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='created_up',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='location',
            name='coordinateX',
            field=models.DecimalField(decimal_places=8, max_digits=10, verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='location',
            name='coordinateY',
            field=models.DecimalField(decimal_places=8, max_digits=11, verbose_name='Долгота'),
        ),
    ]
