# Generated by Django 6.0.1 on 2026-01-20 15:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0004_alter_location_options_location_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='created_up',
        ),
        migrations.AddField(
            model_name='location',
            name='updates_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='coordinateX',
            field=models.DecimalField(decimal_places=8, help_text='Широта должна быть от -90.00000000 до 90.00000000', max_digits=10, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)], verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='location',
            name='coordinateY',
            field=models.DecimalField(decimal_places=8, help_text='Долгота должна быть от -180.00000000 до 180.00000000', max_digits=11, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)], verbose_name='Долгота'),
        ),
    ]
