# Generated by Django 6.0.1 on 2026-01-20 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0006_alter_location_coordinatex_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['updates_at'], 'verbose_name': 'локацию', 'verbose_name_plural': 'Локации'},
        ),
    ]
